name: Deploy to CapRover
on:
  push:
    branches:
      - main

jobs:
  deploy_to_caprover:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Tarball
        run: |
          tar -cvf files.tar ./*

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: "${{ secrets.APP_TOKEN }}"
